"""ファンドマスタCSVを正確な列数で生成するスクリプト"""

import csv
from pathlib import Path

HEADER = [
    "fund_id", "fund_name", "fund_nickname", "company", "rakuten_category",
    "asset_type", "region", "region_japan_pct", "region_us_pct", "region_em_pct",
    "is_index", "is_leveraged", "is_currency_select", "has_currency_hedge",
    "is_monthly_payout", "payout_type",
    "expense_ratio", "aum_oku_yen", "operation_years",
    "fund_score_1y", "fund_score_3y", "fund_score_5y", "fund_score_10y",
    "return_6m", "return_1y", "return_3y", "return_5y", "return_10y", "return_inception",
    "sharpe_1y", "sharpe_3y", "sharpe_5y", "sharpe_10y",
    "stddev_1y", "stddev_3y", "stddev_5y", "stddev_10y",
    "is_nisa_growth_eligible", "data_updated_at", "philosophy_tags",
]

N = ""  # 空値（NaN扱い）

FUNDS = [
    # === 全世界株式（インデックス）===
    {
        "fund_id": "JP90C000H1T1",
        "fund_name": "eMAXIS Slim 全世界株式(オール・カントリー)",
        "fund_nickname": "オルカン",
        "company": "三菱UFJアセット",
        "rakuten_category": "先進国・新興国株式（広域）-為替ヘッジ無し",
        "asset_type": "株式", "region": "world",
        "region_japan_pct": 0.06, "region_us_pct": 0.62, "region_em_pct": 0.11,
        "is_index": True, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 0.05775, "aum_oku_yen": 114519.69, "operation_years": 7.5,
        "fund_score_1y": 4, "fund_score_3y": 4, "fund_score_5y": 4, "fund_score_10y": 0,
        "return_6m": 5.8, "return_1y": 28.5, "return_3y": 22.3, "return_5y": 19.05,
        "return_10y": 14.2, "return_inception": 19.8,
        "sharpe_1y": 1.05, "sharpe_3y": 1.08, "sharpe_5y": 1.17, "sharpe_10y": 1.1,
        "stddev_1y": 17.5, "stddev_3y": 16.8, "stddev_5y": 15.82, "stddev_10y": 14.5,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "passive_index|global_diversified|broad_market|medium_risk",
    },
    {
        "fund_id": "JP90C000R5F8",
        "fund_name": "楽天・プラス・オールカントリー株式インデックス・ファンド",
        "fund_nickname": "楽天・プラス・オールカントリー",
        "company": "楽天",
        "rakuten_category": "先進国・新興国株式（広域）-為替ヘッジ無し",
        "asset_type": "株式", "region": "world",
        "region_japan_pct": 0.06, "region_us_pct": 0.62, "region_em_pct": 0.11,
        "is_index": True, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 0.0561, "aum_oku_yen": 8920.0, "operation_years": 2.0,
        "fund_score_1y": 0, "fund_score_3y": 0, "fund_score_5y": 0, "fund_score_10y": 0,
        "return_6m": 5.9, "return_1y": 28.8, "return_3y": N, "return_5y": 19.20,
        "return_10y": N, "return_inception": N,
        "sharpe_1y": N, "sharpe_3y": N, "sharpe_5y": N, "sharpe_10y": N,
        "stddev_1y": 17.0, "stddev_3y": N, "stddev_5y": 15.5, "stddev_10y": N,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "passive_index|global_diversified|broad_market|medium_risk",
    },
    # === 米国株式（インデックス）===
    {
        "fund_id": "JP90C000GKC6",
        "fund_name": "eMAXIS Slim 米国株式(S&P500)",
        "fund_nickname": N,
        "company": "三菱UFJアセット",
        "rakuten_category": "米国株式-為替ヘッジ無し",
        "asset_type": "株式", "region": "us",
        "region_japan_pct": 0.0, "region_us_pct": 1.0, "region_em_pct": 0.0,
        "is_index": True, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 0.0814, "aum_oku_yen": 113200.36, "operation_years": 7.0,
        "fund_score_1y": 4, "fund_score_3y": 4, "fund_score_5y": 4, "fund_score_10y": 0,
        "return_6m": 6.2, "return_1y": 31.2, "return_3y": 24.1, "return_5y": 21.25,
        "return_10y": 16.8, "return_inception": 22.1,
        "sharpe_1y": 1.08, "sharpe_3y": 1.12, "sharpe_5y": 1.19, "sharpe_10y": 1.15,
        "stddev_1y": 18.2, "stddev_3y": 17.5, "stddev_5y": 17.30, "stddev_10y": 15.8,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "passive_index|us_centric|broad_market|medium_risk",
    },
    {
        "fund_id": "JP90C000H3Q5",
        "fund_name": "SBI・V・S&P500インデックス・ファンド",
        "fund_nickname": N,
        "company": "SBI",
        "rakuten_category": "米国株式-為替ヘッジ無し",
        "asset_type": "株式", "region": "us",
        "region_japan_pct": 0.0, "region_us_pct": 1.0, "region_em_pct": 0.0,
        "is_index": True, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 0.0938, "aum_oku_yen": 26800.0, "operation_years": 6.5,
        "fund_score_1y": 4, "fund_score_3y": 4, "fund_score_5y": 4, "fund_score_10y": 0,
        "return_6m": 6.1, "return_1y": 30.8, "return_3y": 23.8, "return_5y": 20.80,
        "return_10y": 16.5, "return_inception": 21.5,
        "sharpe_1y": 1.06, "sharpe_3y": 1.10, "sharpe_5y": 1.17, "sharpe_10y": 1.12,
        "stddev_1y": 18.0, "stddev_3y": 17.3, "stddev_5y": 17.2, "stddev_10y": 15.7,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "passive_index|us_centric|broad_market|medium_risk",
    },
    {
        "fund_id": "JP90C000FHD2",
        "fund_name": "楽天・全米株式インデックス・ファンド",
        "fund_nickname": "楽天・VTI",
        "company": "楽天",
        "rakuten_category": "米国株式-為替ヘッジ無し",
        "asset_type": "株式", "region": "us",
        "region_japan_pct": 0.0, "region_us_pct": 1.0, "region_em_pct": 0.0,
        "is_index": True, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 0.162, "aum_oku_yen": 24643.37, "operation_years": 8.5,
        "fund_score_1y": 4, "fund_score_3y": 5, "fund_score_5y": 5, "fund_score_10y": 0,
        "return_6m": 5.9, "return_1y": 29.8, "return_3y": 22.8, "return_5y": 19.92,
        "return_10y": 15.5, "return_inception": 20.3,
        "sharpe_1y": 1.03, "sharpe_3y": 1.09, "sharpe_5y": 1.14, "sharpe_10y": 1.08,
        "stddev_1y": 18.0, "stddev_3y": 17.2, "stddev_5y": 17.5, "stddev_10y": 15.5,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "passive_index|us_centric|broad_market|medium_risk",
    },
    {
        "fund_id": "JP90C000N8F6",
        "fund_name": "SBI・V・全米株式インデックス・ファンド",
        "fund_nickname": N,
        "company": "SBI",
        "rakuten_category": "米国株式-為替ヘッジ無し",
        "asset_type": "株式", "region": "us",
        "region_japan_pct": 0.0, "region_us_pct": 1.0, "region_em_pct": 0.0,
        "is_index": True, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 0.0938, "aum_oku_yen": 8950.0, "operation_years": 5.5,
        "fund_score_1y": 4, "fund_score_3y": 4, "fund_score_5y": 4, "fund_score_10y": 0,
        "return_6m": 5.8, "return_1y": 29.5, "return_3y": 22.5, "return_5y": 19.60,
        "return_10y": N, "return_inception": 20.8,
        "sharpe_1y": 1.02, "sharpe_3y": 1.07, "sharpe_5y": 1.12, "sharpe_10y": N,
        "stddev_1y": 18.1, "stddev_3y": 17.4, "stddev_5y": 17.8, "stddev_10y": N,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "passive_index|us_centric|broad_market|medium_risk",
    },
    # NASDAQ-100
    {
        "fund_id": "JP90C000QF22",
        "fund_name": "楽天・プラス・NASDAQ-100インデックス・ファンド",
        "fund_nickname": "楽天・プラス・NASDAQ-100",
        "company": "楽天",
        "rakuten_category": "米国株式-為替ヘッジ無し",
        "asset_type": "株式", "region": "us",
        "region_japan_pct": 0.0, "region_us_pct": 1.0, "region_em_pct": 0.0,
        "is_index": True, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 0.198, "aum_oku_yen": 2094.76, "operation_years": 1.5,
        "fund_score_1y": 0, "fund_score_3y": 0, "fund_score_5y": 0, "fund_score_10y": 0,
        "return_6m": 3.5, "return_1y": 22.1, "return_3y": N, "return_5y": 49.89,
        "return_10y": N, "return_inception": N,
        "sharpe_1y": N, "sharpe_3y": N, "sharpe_5y": N, "sharpe_10y": N,
        "stddev_1y": 21.5, "stddev_3y": N, "stddev_5y": 22.0, "stddev_10y": N,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "passive_index|us_centric|tech_heavy|growth_focused|high_risk",
    },
    {
        "fund_id": "JP90C000P4K1",
        "fund_name": "iFreeNEXT NASDAQ100インデックス",
        "fund_nickname": N,
        "company": "大和",
        "rakuten_category": "米国株式-為替ヘッジ無し",
        "asset_type": "株式", "region": "us",
        "region_japan_pct": 0.0, "region_us_pct": 1.0, "region_em_pct": 0.0,
        "is_index": True, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 0.495, "aum_oku_yen": 5680.0, "operation_years": 7.5,
        "fund_score_1y": 5, "fund_score_3y": 5, "fund_score_5y": 5, "fund_score_10y": 0,
        "return_6m": 4.5, "return_1y": 25.8, "return_3y": 26.2, "return_5y": 23.50,
        "return_10y": 18.2, "return_inception": 22.8,
        "sharpe_1y": 1.05, "sharpe_3y": 1.12, "sharpe_5y": 1.15, "sharpe_10y": 1.08,
        "stddev_1y": 22.0, "stddev_3y": 21.5, "stddev_5y": 22.0, "stddev_10y": 20.5,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "passive_index|us_centric|tech_heavy|growth_focused|high_risk",
    },
    # FANG+
    {
        "fund_id": "JP90C000FZD4",
        "fund_name": "iFreeNEXT FANG+インデックス",
        "fund_nickname": N,
        "company": "大和",
        "rakuten_category": "米国株式-為替ヘッジ無し",
        "asset_type": "株式", "region": "us",
        "region_japan_pct": 0.0, "region_us_pct": 0.95, "region_em_pct": 0.0,
        "is_index": True, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 0.7755, "aum_oku_yen": 11843.54, "operation_years": 7.0,
        "fund_score_1y": 5, "fund_score_3y": 5, "fund_score_5y": 5, "fund_score_10y": 0,
        "return_6m": 8.1, "return_1y": 38.5, "return_3y": 31.2, "return_5y": 28.16,
        "return_10y": 22.5, "return_inception": 26.3,
        "sharpe_1y": 1.15, "sharpe_3y": 1.22, "sharpe_5y": 1.18, "sharpe_10y": 1.12,
        "stddev_1y": 23.5, "stddev_3y": 22.8, "stddev_5y": 25.0, "stddev_10y": 21.5,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "passive_index|us_centric|tech_heavy|thematic|growth_focused|very_high_risk",
    },
    # SOX
    {
        "fund_id": "JP90C000QF30",
        "fund_name": "楽天・プラス・SOXインデックス・ファンド",
        "fund_nickname": "楽天・プラス・SOX",
        "company": "楽天",
        "rakuten_category": "米国株式-為替ヘッジ無し",
        "asset_type": "株式", "region": "us",
        "region_japan_pct": 0.0, "region_us_pct": 1.0, "region_em_pct": 0.0,
        "is_index": True, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 0.176, "aum_oku_yen": 411.8, "operation_years": 1.5,
        "fund_score_1y": 0, "fund_score_3y": 0, "fund_score_5y": 0, "fund_score_10y": 0,
        "return_6m": 2.1, "return_1y": 18.5, "return_3y": N, "return_5y": 164.16,
        "return_10y": N, "return_inception": N,
        "sharpe_1y": N, "sharpe_3y": N, "sharpe_5y": N, "sharpe_10y": N,
        "stddev_1y": 28.5, "stddev_3y": N, "stddev_5y": 30.0, "stddev_10y": N,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "passive_index|us_centric|tech_heavy|thematic|very_high_risk",
    },
    # === 米国株式（アクティブ・配当）===
    {
        "fund_id": "JP90C000R6N1",
        "fund_name": "楽天・シュワブ・高配当株式・米国ファンド(四半期決算型)",
        "fund_nickname": "楽天・SCHD",
        "company": "楽天",
        "rakuten_category": "米国株式-為替ヘッジ無し",
        "asset_type": "株式", "region": "us",
        "region_japan_pct": 0.0, "region_us_pct": 1.0, "region_em_pct": 0.0,
        "is_index": False, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "income",
        "expense_ratio": 0.1238, "aum_oku_yen": 2229.17, "operation_years": 1.5,
        "fund_score_1y": 0, "fund_score_3y": 0, "fund_score_5y": 0, "fund_score_10y": 0,
        "return_6m": 1.8, "return_1y": 14.2, "return_3y": N, "return_5y": 38.60,
        "return_10y": N, "return_inception": N,
        "sharpe_1y": N, "sharpe_3y": N, "sharpe_5y": N, "sharpe_10y": N,
        "stddev_1y": 18.5, "stddev_3y": N, "stddev_5y": 19.0, "stddev_10y": N,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "smart_beta|us_centric|dividend_focused|medium_risk",
    },
    {
        "fund_id": "JP90C000S1R2",
        "fund_name": "JPモルガン・米国株式・プレミアム・インカム・ファンド",
        "fund_nickname": "JEPQ",
        "company": "JPモルガン",
        "rakuten_category": "米国株式-為替ヘッジ無し",
        "asset_type": "株式", "region": "us",
        "region_japan_pct": 0.0, "region_us_pct": 1.0, "region_em_pct": 0.0,
        "is_index": False, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": True, "payout_type": "income",
        "expense_ratio": 0.7315, "aum_oku_yen": 1850.0, "operation_years": 2.0,
        "fund_score_1y": 0, "fund_score_3y": 0, "fund_score_5y": 0, "fund_score_10y": 0,
        "return_6m": 2.5, "return_1y": 15.8, "return_3y": N, "return_5y": 35.20,
        "return_10y": N, "return_inception": N,
        "sharpe_1y": N, "sharpe_3y": N, "sharpe_5y": N, "sharpe_10y": N,
        "stddev_1y": 20.0, "stddev_3y": N, "stddev_5y": 21.0, "stddev_10y": N,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "active_diversified|us_centric|dividend_focused|tech_heavy|high_risk",
    },
    {
        "fund_id": "JP90C000J5A3",
        "fund_name": "アライアンス・バーンスタイン・米国成長株投信Dコース",
        "fund_nickname": N,
        "company": "アライアンスバーンスタイン",
        "rakuten_category": "米国株式-為替ヘッジ無し",
        "asset_type": "株式", "region": "us",
        "region_japan_pct": 0.0, "region_us_pct": 0.95, "region_em_pct": 0.0,
        "is_index": False, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 1.727, "aum_oku_yen": 22500.0, "operation_years": 15.0,
        "fund_score_1y": 5, "fund_score_3y": 5, "fund_score_5y": 5, "fund_score_10y": 4,
        "return_6m": 5.8, "return_1y": 30.2, "return_3y": 25.5, "return_5y": 22.80,
        "return_10y": 18.5, "return_inception": 21.2,
        "sharpe_1y": 1.08, "sharpe_3y": 1.15, "sharpe_5y": 1.18, "sharpe_10y": 1.12,
        "stddev_1y": 22.0, "stddev_3y": 21.5, "stddev_5y": 21.8, "stddev_10y": 20.2,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "active_concentrated|us_centric|growth_focused|tech_heavy|high_risk",
    },
    # === 国内株式（インデックス）===
    {
        "fund_id": "JP90C000ENA9",
        "fund_name": "eMAXIS Slim 国内株式(TOPIX)",
        "fund_nickname": N,
        "company": "三菱UFJアセット",
        "rakuten_category": "国内株式",
        "asset_type": "株式", "region": "japan",
        "region_japan_pct": 1.0, "region_us_pct": 0.0, "region_em_pct": 0.0,
        "is_index": True, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 0.143, "aum_oku_yen": 6719.0, "operation_years": 7.5,
        "fund_score_1y": 3, "fund_score_3y": 3, "fund_score_5y": 3, "fund_score_10y": 0,
        "return_6m": 3.2, "return_1y": 18.5, "return_3y": 14.2, "return_5y": 16.68,
        "return_10y": N, "return_inception": 15.5,
        "sharpe_1y": 0.82, "sharpe_3y": 0.88, "sharpe_5y": 0.92, "sharpe_10y": N,
        "stddev_1y": 14.8, "stddev_3y": 15.2, "stddev_5y": 15.0, "stddev_10y": N,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "passive_index|japan_centric|broad_market|medium_risk",
    },
    {
        "fund_id": "JP90C000FXV1",
        "fund_name": "ニッセイ日経平均インデックスファンド",
        "fund_nickname": N,
        "company": "ニッセイ",
        "rakuten_category": "国内株式",
        "asset_type": "株式", "region": "japan",
        "region_japan_pct": 1.0, "region_us_pct": 0.0, "region_em_pct": 0.0,
        "is_index": True, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 0.1133, "aum_oku_yen": 4250.0, "operation_years": 8.0,
        "fund_score_1y": 3, "fund_score_3y": 3, "fund_score_5y": 3, "fund_score_10y": 0,
        "return_6m": 3.5, "return_1y": 19.2, "return_3y": 14.8, "return_5y": 17.50,
        "return_10y": 16.0, "return_inception": N,
        "sharpe_1y": 0.85, "sharpe_3y": 0.90, "sharpe_5y": 0.95, "sharpe_10y": N,
        "stddev_1y": 14.5, "stddev_3y": 15.0, "stddev_5y": 14.8, "stddev_10y": N,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "passive_index|japan_centric|broad_market|medium_risk",
    },
    {
        "fund_id": "JP90C000B1P9",
        "fund_name": "eMAXIS Slim 国内株式(日経平均)",
        "fund_nickname": N,
        "company": "三菱UFJアセット",
        "rakuten_category": "国内株式",
        "asset_type": "株式", "region": "japan",
        "region_japan_pct": 1.0, "region_us_pct": 0.0, "region_em_pct": 0.0,
        "is_index": True, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 0.143, "aum_oku_yen": 3890.0, "operation_years": 7.0,
        "fund_score_1y": 3, "fund_score_3y": 3, "fund_score_5y": 3, "fund_score_10y": 0,
        "return_6m": 3.4, "return_1y": 19.0, "return_3y": 14.6, "return_5y": 17.20,
        "return_10y": 15.8, "return_inception": N,
        "sharpe_1y": 0.83, "sharpe_3y": 0.89, "sharpe_5y": 0.93, "sharpe_10y": N,
        "stddev_1y": 14.6, "stddev_3y": 15.1, "stddev_5y": 14.9, "stddev_10y": N,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "passive_index|japan_centric|broad_market|medium_risk",
    },
    # === 国内高配当 ===
    {
        "fund_id": "JP90C000Q2F1",
        "fund_name": "SBI日本高配当株式(分配)ファンド(年4回決算型)",
        "fund_nickname": N,
        "company": "SBI",
        "rakuten_category": "国内株式",
        "asset_type": "株式", "region": "japan",
        "region_japan_pct": 1.0, "region_us_pct": 0.0, "region_em_pct": 0.0,
        "is_index": False, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "income",
        "expense_ratio": 0.099, "aum_oku_yen": 4850.0, "operation_years": 3.0,
        "fund_score_1y": 0, "fund_score_3y": 0, "fund_score_5y": 0, "fund_score_10y": 0,
        "return_6m": 4.2, "return_1y": 22.8, "return_3y": N, "return_5y": 18.50,
        "return_10y": N, "return_inception": N,
        "sharpe_1y": N, "sharpe_3y": N, "sharpe_5y": N, "sharpe_10y": N,
        "stddev_1y": 16.5, "stddev_3y": N, "stddev_5y": 17.0, "stddev_10y": N,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "smart_beta|japan_centric|dividend_focused|medium_risk",
    },
    # === 全世界アクティブ ===
    {
        "fund_id": "JP90C000MED5",
        "fund_name": "WCM 世界成長株厳選ファンド(予想分配金提示型)",
        "fund_nickname": "ネクスト・ジェネレーション",
        "company": "朝日ライフ",
        "rakuten_category": "先進国株式（広域）-為替ヘッジ無し",
        "asset_type": "株式", "region": "world",
        "region_japan_pct": 0.0, "region_us_pct": 0.65, "region_em_pct": 0.0,
        "is_index": False, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 1.958, "aum_oku_yen": 3568.86, "operation_years": 5.5,
        "fund_score_1y": 5, "fund_score_3y": 5, "fund_score_5y": 5, "fund_score_10y": 0,
        "return_6m": 6.5, "return_1y": 32.1, "return_3y": 27.8, "return_5y": 45.72,
        "return_10y": N, "return_inception": N,
        "sharpe_1y": 1.12, "sharpe_3y": 1.18, "sharpe_5y": 1.22, "sharpe_10y": N,
        "stddev_1y": 20.5, "stddev_3y": N, "stddev_5y": 20.87, "stddev_10y": N,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "active_concentrated|developed_only|growth_focused|high_risk",
    },
    {
        "fund_id": "JP90C000N4D7",
        "fund_name": "eMAXIS Slim 先進国株式インデックス",
        "fund_nickname": N,
        "company": "三菱UFJアセット",
        "rakuten_category": "先進国株式（広域）-為替ヘッジ無し",
        "asset_type": "株式", "region": "world",
        "region_japan_pct": 0.0, "region_us_pct": 0.65, "region_em_pct": 0.0,
        "is_index": True, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 0.09889, "aum_oku_yen": 28500.0, "operation_years": 7.5,
        "fund_score_1y": 4, "fund_score_3y": 4, "fund_score_5y": 4, "fund_score_10y": 0,
        "return_6m": 5.5, "return_1y": 27.8, "return_3y": 21.5, "return_5y": 18.50,
        "return_10y": 14.8, "return_inception": 19.2,
        "sharpe_1y": 1.02, "sharpe_3y": 1.06, "sharpe_5y": 1.12, "sharpe_10y": 1.05,
        "stddev_1y": 17.8, "stddev_3y": 17.0, "stddev_5y": 16.5, "stddev_10y": 15.2,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "passive_index|developed_only|broad_market|medium_risk",
    },
    {
        "fund_id": "JP90C000P8E9",
        "fund_name": "インベスコ 世界厳選株式オープン(毎月決算型)",
        "fund_nickname": "世界のベスト",
        "company": "インベスコ",
        "rakuten_category": "先進国株式（広域）-為替ヘッジ無し",
        "asset_type": "株式", "region": "world",
        "region_japan_pct": 0.0, "region_us_pct": 0.55, "region_em_pct": 0.0,
        "is_index": False, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": True, "payout_type": "income",
        "expense_ratio": 1.903, "aum_oku_yen": 35800.0, "operation_years": 18.5,
        "fund_score_1y": 4, "fund_score_3y": 4, "fund_score_5y": 4, "fund_score_10y": 3,
        "return_6m": 4.2, "return_1y": 22.5, "return_3y": 18.8, "return_5y": 16.50,
        "return_10y": 12.5, "return_inception": 15.8,
        "sharpe_1y": 0.88, "sharpe_3y": 0.92, "sharpe_5y": 0.95, "sharpe_10y": 0.88,
        "stddev_1y": 16.5, "stddev_3y": 16.2, "stddev_5y": 16.0, "stddev_10y": 15.0,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "active_diversified|developed_only|quality|dividend_focused|medium_risk",
    },
    # === 新興国株式 ===
    {
        "fund_id": "JP90C000CX77",
        "fund_name": "eMAXIS Slim 新興国株式インデックス",
        "fund_nickname": N,
        "company": "三菱UFJアセット",
        "rakuten_category": "新興国株式-為替ヘッジ無し",
        "asset_type": "株式", "region": "em",
        "region_japan_pct": 0.0, "region_us_pct": 0.05, "region_em_pct": 0.8,
        "is_index": True, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 0.1518, "aum_oku_yen": 6520.0, "operation_years": 7.5,
        "fund_score_1y": 3, "fund_score_3y": 3, "fund_score_5y": 3, "fund_score_10y": 0,
        "return_6m": 2.1, "return_1y": 12.5, "return_3y": 9.8, "return_5y": 11.20,
        "return_10y": 8.5, "return_inception": 10.5,
        "sharpe_1y": 0.65, "sharpe_3y": 0.70, "sharpe_5y": 0.72, "sharpe_10y": 0.68,
        "stddev_1y": 18.5, "stddev_3y": 18.0, "stddev_5y": 17.8, "stddev_10y": 17.0,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "passive_index|em_centric|broad_market|high_risk",
    },
    {
        "fund_id": "JP90C000T5P0",
        "fund_name": "SBI・iShares・インド株式インデックス・ファンド",
        "fund_nickname": N,
        "company": "SBI",
        "rakuten_category": "新興国株式-為替ヘッジ無し",
        "asset_type": "株式", "region": "em",
        "region_japan_pct": 0.0, "region_us_pct": 0.0, "region_em_pct": 1.0,
        "is_index": True, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 0.4638, "aum_oku_yen": 2180.0, "operation_years": 2.5,
        "fund_score_1y": 0, "fund_score_3y": 0, "fund_score_5y": 0, "fund_score_10y": 0,
        "return_6m": 5.8, "return_1y": 28.5, "return_3y": N, "return_5y": 35.50,
        "return_10y": N, "return_inception": N,
        "sharpe_1y": N, "sharpe_3y": N, "sharpe_5y": N, "sharpe_10y": N,
        "stddev_1y": 22.5, "stddev_3y": N, "stddev_5y": 24.0, "stddev_10y": N,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "passive_index|em_centric|thematic|high_risk",
    },
    # === 債券系 ===
    {
        "fund_id": "JP90C000B2P5",
        "fund_name": "eMAXIS Slim 先進国債券インデックス",
        "fund_nickname": N,
        "company": "三菱UFJアセット",
        "rakuten_category": "先進国債券-為替ヘッジ無し",
        "asset_type": "債券", "region": "world",
        "region_japan_pct": 0.0, "region_us_pct": 0.45, "region_em_pct": 0.0,
        "is_index": True, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 0.154, "aum_oku_yen": 3200.0, "operation_years": 7.5,
        "fund_score_1y": 3, "fund_score_3y": 3, "fund_score_5y": 3, "fund_score_10y": 0,
        "return_6m": 1.2, "return_1y": 5.8, "return_3y": 3.2, "return_5y": 3.50,
        "return_10y": 5.2, "return_inception": 4.8,
        "sharpe_1y": 0.45, "sharpe_3y": 0.38, "sharpe_5y": 0.42, "sharpe_10y": 0.55,
        "stddev_1y": 7.5, "stddev_3y": 7.2, "stddev_5y": 7.0, "stddev_10y": 7.8,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "passive_index|global_diversified|defensive|low_risk",
    },
    {
        "fund_id": "JP90C000D3X2",
        "fund_name": "eMAXIS Slim 国内債券インデックス",
        "fund_nickname": N,
        "company": "三菱UFJアセット",
        "rakuten_category": "国内債券",
        "asset_type": "債券", "region": "japan",
        "region_japan_pct": 1.0, "region_us_pct": 0.0, "region_em_pct": 0.0,
        "is_index": True, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 0.132, "aum_oku_yen": 2850.0, "operation_years": 7.0,
        "fund_score_1y": 3, "fund_score_3y": 3, "fund_score_5y": 3, "fund_score_10y": 0,
        "return_6m": 0.5, "return_1y": 2.1, "return_3y": 1.8, "return_5y": 2.10,
        "return_10y": 2.5, "return_inception": 2.2,
        "sharpe_1y": 0.35, "sharpe_3y": 0.32, "sharpe_5y": 0.38, "sharpe_10y": 0.42,
        "stddev_1y": 3.2, "stddev_3y": 3.0, "stddev_5y": 3.5, "stddev_10y": 3.2,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "passive_index|japan_centric|defensive|low_risk",
    },
    # === バランス系 ===
    {
        "fund_id": "JP90C000FBSD",
        "fund_name": "eMAXIS Slim バランス(8資産均等型)",
        "fund_nickname": N,
        "company": "三菱UFJアセット",
        "rakuten_category": "バランス-為替ヘッジ無し",
        "asset_type": "バランス", "region": "world",
        "region_japan_pct": 0.12, "region_us_pct": 0.25, "region_em_pct": 0.05,
        "is_index": True, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 0.143, "aum_oku_yen": 14500.0, "operation_years": 7.5,
        "fund_score_1y": 3, "fund_score_3y": 3, "fund_score_5y": 3, "fund_score_10y": 0,
        "return_6m": 2.8, "return_1y": 12.5, "return_3y": 9.2, "return_5y": 9.80,
        "return_10y": 8.5, "return_inception": 10.2,
        "sharpe_1y": 0.72, "sharpe_3y": 0.75, "sharpe_5y": 0.78, "sharpe_10y": 0.72,
        "stddev_1y": 9.5, "stddev_3y": 9.2, "stddev_5y": 9.0, "stddev_10y": 8.8,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "passive_index|global_diversified|broad_market|low_risk",
    },
    {
        "fund_id": "JP90C000G2C4",
        "fund_name": "楽天・インデックス・バランス・ファンド(均等型)",
        "fund_nickname": N,
        "company": "楽天",
        "rakuten_category": "バランス-為替ヘッジ無し",
        "asset_type": "バランス", "region": "world",
        "region_japan_pct": 0.1, "region_us_pct": 0.3, "region_em_pct": 0.05,
        "is_index": True, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 0.132, "aum_oku_yen": 4200.0, "operation_years": 6.0,
        "fund_score_1y": 3, "fund_score_3y": 3, "fund_score_5y": 3, "fund_score_10y": 0,
        "return_6m": 3.0, "return_1y": 13.2, "return_3y": 9.8, "return_5y": 10.50,
        "return_10y": N, "return_inception": N,
        "sharpe_1y": 0.75, "sharpe_3y": 0.78, "sharpe_5y": 0.82, "sharpe_10y": N,
        "stddev_1y": 9.8, "stddev_3y": 9.5, "stddev_5y": 9.2, "stddev_10y": N,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "passive_index|global_diversified|broad_market|low_risk",
    },
    # === 国内アクティブ ===
    {
        "fund_id": "JP90C000L7B4",
        "fund_name": "コモンズ30ファンド",
        "fund_nickname": N,
        "company": "コモンズ投信",
        "rakuten_category": "国内株式",
        "asset_type": "株式", "region": "japan",
        "region_japan_pct": 1.0, "region_us_pct": 0.0, "region_em_pct": 0.0,
        "is_index": False, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 1.078, "aum_oku_yen": 950.0, "operation_years": 17.0,
        "fund_score_1y": 4, "fund_score_3y": 4, "fund_score_5y": 4, "fund_score_10y": 3,
        "return_6m": 2.5, "return_1y": 16.5, "return_3y": 12.8, "return_5y": 14.50,
        "return_10y": 11.2, "return_inception": 13.8,
        "sharpe_1y": 0.78, "sharpe_3y": 0.82, "sharpe_5y": 0.88, "sharpe_10y": 0.82,
        "stddev_1y": 13.5, "stddev_3y": 13.8, "stddev_5y": 14.0, "stddev_10y": 13.2,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "active_concentrated|japan_centric|quality|medium_risk",
    },
    {
        "fund_id": "JP90C000M9C5",
        "fund_name": "ひふみプラス",
        "fund_nickname": N,
        "company": "レオス",
        "rakuten_category": "国内株式",
        "asset_type": "株式", "region": "japan",
        "region_japan_pct": 0.9, "region_us_pct": 0.05, "region_em_pct": 0.0,
        "is_index": False, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 1.078, "aum_oku_yen": 7200.0, "operation_years": 14.5,
        "fund_score_1y": 3, "fund_score_3y": 3, "fund_score_5y": 3, "fund_score_10y": 3,
        "return_6m": 1.8, "return_1y": 12.5, "return_3y": 10.2, "return_5y": 12.80,
        "return_10y": 13.5, "return_inception": 12.5,
        "sharpe_1y": 0.65, "sharpe_3y": 0.70, "sharpe_5y": 0.75, "sharpe_10y": 0.78,
        "stddev_1y": 14.5, "stddev_3y": 14.2, "stddev_5y": 14.8, "stddev_10y": 13.8,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "active_diversified|japan_centric|quality|medium_risk",
    },
    # === レバレッジ（フィルタ除外用）===
    {
        "fund_id": "JP90C000CCD0",
        "fund_name": "楽天日本株4.3倍ブル",
        "fund_nickname": N,
        "company": "楽天",
        "rakuten_category": "分類対象外",
        "asset_type": "株式", "region": "japan",
        "region_japan_pct": 1.0, "region_us_pct": 0.0, "region_em_pct": 0.0,
        "is_index": False, "is_leveraged": True, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 1.243, "aum_oku_yen": 1303.37, "operation_years": 11.0,
        "fund_score_1y": 0, "fund_score_3y": 0, "fund_score_5y": 0, "fund_score_10y": 0,
        "return_6m": -12.5, "return_1y": -45.2, "return_3y": N, "return_5y": 33.72,
        "return_10y": N, "return_inception": N,
        "sharpe_1y": N, "sharpe_3y": 0.76, "sharpe_5y": N, "sharpe_10y": N,
        "stddev_1y": 80.5, "stddev_3y": 84.37, "stddev_5y": N, "stddev_10y": N,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "leverage_warning|japan_centric|very_high_risk",
    },
    # === NASDAQ ニッセイ ===
    {
        "fund_id": "JP90C000K2D8",
        "fund_name": "ニッセイNASDAQ100インデックスファンド",
        "fund_nickname": N,
        "company": "ニッセイ",
        "rakuten_category": "米国株式-為替ヘッジ無し",
        "asset_type": "株式", "region": "us",
        "region_japan_pct": 0.0, "region_us_pct": 1.0, "region_em_pct": 0.0,
        "is_index": True, "is_leveraged": False, "is_currency_select": False,
        "has_currency_hedge": False, "is_monthly_payout": False, "payout_type": "none",
        "expense_ratio": 0.2035, "aum_oku_yen": 3250.0, "operation_years": 3.5,
        "fund_score_1y": 0, "fund_score_3y": 0, "fund_score_5y": 0, "fund_score_10y": 0,
        "return_6m": 4.2, "return_1y": 24.5, "return_3y": N, "return_5y": 22.80,
        "return_10y": N, "return_inception": N,
        "sharpe_1y": N, "sharpe_3y": N, "sharpe_5y": N, "sharpe_10y": N,
        "stddev_1y": 22.5, "stddev_3y": N, "stddev_5y": 21.8, "stddev_10y": N,
        "is_nisa_growth_eligible": True, "data_updated_at": "2026-05-01",
        "philosophy_tags": "passive_index|us_centric|tech_heavy|growth_focused|high_risk",
    },
]


def main():
    out_path = Path(__file__).parent.parent / "data" / "fund_master.csv"
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=HEADER)
        writer.writeheader()
        for fund in FUNDS:
            row = {col: fund.get(col, "") for col in HEADER}
            writer.writerow(row)
    print(f"生成完了: {out_path} ({len(FUNDS)}本)")


if __name__ == "__main__":
    main()
